apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-pod
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-volume
  labels:
    app: nginx-app
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/devopscode0/datat/app-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  labels:
    app: nginx-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: nginx-app
spec:
  volumes:
    - name: nginx-pv-volume
      persistentVolumeClaim:
       claimName: nginx-pv-claim
  containers: 
    - image: nginx
      name: nginx-pod
      ports:
      - containerPort: 80
        name: "nginx-server"
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-pv-volume
